### ISSUE TITLE
Document how to use this generator

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-connect-model#2]
Cool idea! Currently it shows how to add the generator to the project, but not the command to generator a new model using this.

**Comment by marshallswain** [comment]
It's it the same command?  `donejs add connect-model` generates the model, no?

**Comment by matthewp** [comment]
Brain lapse.

**Comment by matthewp** [comment]
Well, it does take the name though.

```
donejs add connect-model order
```

to create an order model.
